version: "3"

services:
  static:
    build: .
    ports:
      - ${NGINX_IP}:80:80
      - ${NGINX_IP}:8080:8080
    restart: unless-stopped
  api:
    build: ./server
    # Expose server to other containers in compose
    expose: 
      - 8080
    volumes:
      - ./server/data:/app/data
    restart: unless-stopped

