version: "3"

services:
  static:
    build: .
    ports:
      - 80:80
    restart: unless-stopped
  api:
    build: ./server
    expose: 
      - 8080
    volumes: 
      - ./server/persist:/app/persist
    restart: unless-stopped

