version: "3"

services:
  static:
    build: .
    ports:
      - 80:80
    restart: unless-stopped
  api:
    build: ./server
    # Expose server to other containers in compose
    expose: 
      - 8080
    volumes:
      - ./server/data:/app/data
    restart: unless-stopped

